id = "yaru"
name = "Yaru"
version = "1.0.0"
schema_version = 1
description = "An Ubuntu Yaru styled theme for Zed, inspired by Paulo Fino's Adwaita Theme"
repository = "https://github.com/senni-huemwang/yaru-zed-theme"
authors = ["Senni <shuemwang.han@gmail.com>"]
themes = ["themes/yaru.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
